image: docker:stable
services:
- docker:dind

stages:
- deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

deploy to server:
  stage: deploy
  before_script:
    - apk update && apk add openssh-client rsync --no-cache
    - echo "$SSH_PRIVATE_KEY" >> key.pem
    - chmod 400 key.pem
  script:
    - ssh -i key.pem -o 'StrictHostKeyChecking no' eqonaq@94.247.133.122 "git -C /home/eqonaq/www/guest.eqonaq.kz pull origin master && \"cd www/guest.eqonaq && npm install\""
    - ssh -i key.pem -o 'StrictHostKeyChecking no' eqonaq@94.247.133.122 "docker exec -i php-fpm_prod bash -c \"cd guest.eqonaq && npm run build\""
  after_script:
    - rm key.pem
  only:
    - master
