image: docker:stable
services:
- docker:dind

stages:
- deploy-prod
- deploy-stage

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

deploy to prod server:
  stage: deploy-prod
  before_script:
    - apk update && apk add openssh-client rsync --no-cache
    - echo "$SSH_PRIVATE_KEY" >> key.pem
    - chmod 400 key.pem
  script:
    - ssh -i key.pem -o 'StrictHostKeyChecking no' eqonaq@94.247.133.122 "cd /home/eqonaq/www/guest.eqonaq && git checkout ."
    - ssh -i key.pem -o 'StrictHostKeyChecking no' eqonaq@94.247.133.122 "git -C /home/eqonaq/www/guest.eqonaq pull origin master"
    - ssh -i key.pem -o 'StrictHostKeyChecking no' eqonaq@94.247.133.122 "docker exec -i php-fpm_prod bash -c \"cd guest.eqonaq && npm run build\""
  after_script:
    - rm key.pem
  only:
    - master

deploy to stage server:
  stage: deploy-stage
  before_script:
    - apk update && apk add openssh-client rsync --no-cache
    - echo "$SSH_PRIVATE_KEY_BETA" >> key.pem
    - chmod 400 key.pem
  script:
    - ssh -i key.pem -o 'StrictHostKeyChecking no' eqonaq@195.210.47.190 -p 2232 "cd /home/eqonaq/www/guest.stage.eqonaq.kz && git checkout ."
    - ssh -i key.pem -o 'StrictHostKeyChecking no' eqonaq@195.210.47.190 -p 2232 "git -C /home/eqonaq/www/guest.stage.eqonaq.kz pull origin master"
    - ssh -i key.pem -o 'StrictHostKeyChecking no' eqonaq@195.210.47.190 -p 2232 "cd /home/eqonaq/www/guest.stage.eqonaq.kz && npm install && npm run build"
  after_script:
    - rm key.pem
  only:
    - master